### ISSUE TITLE
Unable to launch MBS on xiaomi devices

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#174]
Could it be that the recent changes in shell has broken the fragile regex matching of adb output...
This happened on mac:
```
$ snippet_shell.py com.google.android.mobly.snippet.bundled
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/snippet_shell.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 64, in <module>
    SnippetShell(args.package[0]).main(args.serial)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 91, in main
    self.start_console()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 76, in start_console
    self._start_services(console_env)
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 41, in _start_services
    self._ad.load_snippet(name='snippet', package=self._package)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 629, in load_snippet
    self._start_jsonrpc_client(client)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 660, in _start_jsonrpc_client
    client.check_app_installed()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/snippet_client.py", line 110, in check_app_installed
    target_name = match.group(3)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by adorokhine** [comment]
Launching snippets still works for me, so I think I'd need to see the test_run_details.txt on this one.

**Comment by xpconanfan** [comment]
Im using snippet shell. I think this might be Mac specific.

**Comment by adorokhine** [comment]
Can you turn up the logging to DEBUG then? I think I'd need to see what
commands are going out and what's coming back.

**Comment by xpconanfan** [comment]
It works on nexus...
Looks like it's an NBU specific issue...

**Comment by xpconanfan** [comment]
So from what I can tell, this might a regression from the changes in shell.
We run the following cmd to find snippet package:
```
ad.adb.shell(r'pm list package | tr -d "\r" | grep ^package:%s$' % 'com.google.android.mobly.snippet.bundled')
```

In the old shell, the `tr` and `grep` were done on the host machine, but now it looks like `tr` and `grep` are executed on the Android device's shell. Some NBU devices don't have `tr`, causing the cmd to fail with `b'/system/bin/sh: tr: not found\r\n'`.

Suggestions?

**Comment by xpconanfan** [comment]
Ok, we just need to use `shell=True` for grep wrapper
