### ISSUE TITLE
Error in tearing down `AndroidDevice`'s logcat service

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#267]
To reproduce, have a bare minimum test that gets one `AndroidDevice`, calls one adb cmd and exit.
Like:
```
class SomeTest(base_test.BaseTestClase):
  def setup_class(self):
    self.dut = self.register_controller(android_device)[0]
  def test_a(self):
    self.dut.adb.reboot()
```

Every time this test runs, we get a stacktrace like this:
```
 07-20 18:59:35.677 ERROR [AndroidDevice|84B7N15A28012457] Failed to stop adb logcat.
Traceback (most recent call last):
  File ".../mobly/controllers/android_device.py", line 445, in stop_services
    self.stop_adb_logcat()
  File ".../mobly/controllers/android_device.py", line 773, in stop_adb_logcat
    utils.stop_standing_subprocess(self._adb_logcat_process)
  File ".../mobly/utils.py", line 355, in stop_standing_subprocess
    _assert_subprocess_running(proc)
  File ".../mobly/utils.py", line 294, in _assert_subprocess_running
    " stdout: %s" % (proc.pid, ret, err, out))
Error: Process 6383 has terminated. ret: 0, stderr: , stdout:
```

**Comment by xpconanfan** [comment]
Fixed by #288
