### ISSUE TITLE
`utils._assert_subprocess_running` throws `ValueError`

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#288]
If the process died, we try to call `p.communicate` to get info from the process.
Then `communicate` would sometimes fail with ValueError saying it's trying to do I/O operation on a closed file.

**Comment by xpconanfan** [comment]
Stacktrace
```
I 01:49:36:820 UTC Traceback (most recent call last):
I 01:49:36:820 UTC   File "mobly/base_test.py", line 355, in exec_one_test
I 01:49:36:820 UTC     self._teardown_test(test_name)
I 01:49:36:820 UTC   File "mobly/base_test.py", line 218, in _teardown_test
I 01:49:36:820 UTC     self.teardown_test()
I 01:49:36:821 UTC   File "...", line 226, in teardown_test
I 01:49:36:821 UTC     self._StopAdbLogAndCreateExcerpt(self.dut_b)
I 01:49:36:821 UTC   File "...", line 201, in _StopAdbLogAndCreateExcerpt
I 01:49:36:821 UTC     device.stop_adb_logcat()
I 01:49:36:821 UTC   File "mobly/controllers/android_device.py", line 844, in stop_adb_logcat
I 01:49:36:821 UTC     utils.stop_standing_subprocess(self._adb_logcat_process)
I 01:49:36:821 UTC   File "mobly/utils.py", line 356, in stop_standing_subprocess
I 01:49:36:821 UTC     _assert_subprocess_running(proc)
I 01:49:36:822 UTC   File "mobly/utils.py", line 293, in _assert_subprocess_running
I 01:49:36:822 UTC     out, err = proc.communicate()
I 01:49:36:822 UTC   File "v2_7/python27.zip.tmp/subprocess.py", line 958, in communicate
I 01:49:36:822 UTC     stdout, stderr = self._communicate(input, endtime, timeout)
I 01:49:36:822 UTC   File "v2_7/python27.zip.tmp/subprocess.py", line 1744, in _communicate
I 01:49:36:822 UTC     orig_timeout)
I 01:49:36:822 UTC   File "v2_7/python27.zip.tmp/subprocess.py", line 1800, in _communicate_with_poll
I 01:49:36:822 UTC     register_and_append(self.stdout, select_POLLIN_POLLPRI)
I 01:49:36:822 UTC   File "v2_7/python27.zip.tmp/subprocess.py", line 1779, in register_and_append
I 01:49:36:823 UTC     poller.register(file_obj.fileno(), eventmask)
I 01:49:36:823 UTC ValueError: I/O operation on closed file
```

**Comment by xpconanfan** [comment]
This might be caused by `start_standing_process` doing this `proc.stdin.close()`

**Comment by xpconanfan** [comment]
`_assert_subprocess_running` adds no value for our tests, and it keeps throwing errors when it doesn't need to. I'm gonna take it out

**Comment by xpconanfan** [comment]
The original idea was that we'll do a check to make sure the subprocess was indeed started in `start_standing_subprocess`. But the implementation is flimsy and unreliable.

To fix all the issues:
* Remove `_assert_subprocess_running`.
* `start_standing_subprocess` will return a `psutil.Process`, which has a lot of useful methods like `is_running`. So users can do this check themselves if they want to.
* Better error msg for `stop_standing_subprocess`
