### ISSUE TITLE
`snippet_shell` is broken?

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#326]
When trying to launch snippet shell:
```
$ snippet_shell.py --mbs
INFO:root: Launching snippet apk com.google.android.mobly.snippet.bundled with protocol 1.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/snippet_shell.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 84, in <module>
    SnippetShell(package).main(args.serial)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 88, in main
    self.start_console()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_shell_base.py", line 73, in start_console
    self._start_services(console_env)
  File "/Users/angli/Developer/mobly/tools/snippet_shell.py", line 43, in _start_services
    self._ad.load_snippet(name='snippet', package=self._package)
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 738, in load_snippet
    raise e
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 729, in load_snippet
    client.start_app_and_connect()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device_lib/snippet_client.py", line 109, in start_app_and_connect
    raise ProtocolVersionError(line)
mobly.controllers.android_device_lib.snippet_client.ProtocolVersionError: INSTRUMENTATION_RESULT: shortMsg=Process crashed.
```

In adb log:
```
--------- beginning of crash
08-30 12:09:01.412  8791  8806 E AndroidRuntime: FATAL EXCEPTION: Instr: com.google.android.mobly.snippet.SnippetRunner
08-30 12:09:01.412  8791  8806 E AndroidRuntime: Process: com.google.android.mobly.snippet.bundled, PID: 8791
08-30 12:09:01.412  8791  8806 E AndroidRuntime: java.lang.IllegalArgumentException: "--e port <port>" was not specified
08-30 12:09:01.412  8791  8806 E AndroidRuntime: 	at com.google.android.mobly.snippet.SnippetRunner.onStart(SnippetRunner.java:82)
08-30 12:09:01.412  8791  8806 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
08-30 12:09:01.415  8791  8806 I Process : Sending signal. PID: 8791 SIG: 9
08-30 12:09:01.422   880   904 I ActivityManager: Process com.google.android.mobly.snippet.bundled (pid 8791) has died: fore FGS
08-30 12:09:01.422   880   904 W ActivityManager: Crash of app com.google.android.mobly.snippet.bundled running instrumentation ComponentInfo{com.google.android.mobly.snippet.bundled/com.google.android.mobly.snippet.SnippetRunner}
```

**Comment by xpconanfan** [comment]
Looks like this is due to version mismatch.

**Comment by HaveF** [comment]
@xpconanfan 
Sorry to bother you.

If version mismatch, I should check the [google/mobly-bundled-snippets](https://github.com/google/mobly-bundled-snippets)'s [build.gradle](https://github.com/google/mobly-bundled-snippets/blob/master/build.gradle#L35), right?

What can I do else?

**Comment by xpconanfan** [comment]
You should make sure the snippet client you use is the latest, and that your snippet apk is built with the latest snippet library

**Comment by HaveF** [comment]
@xpconanfan Thanks for your response. 😃 
I retry everything, it seems still `ProtocolVersionError`. Install mobly of git version, build the mobly-bundled-snippets with [`targetSdkVersion 26`](https://github.com/google/mobly-bundled-snippets/blob/master/build.gradle#L41) (for my phone is android 8.0.0), then install on the phone `adb install -d -r -g ./build/outputs/apk/debug/mobly-bundled-snippets-debug.apk`

When I try `python mobly\tools\snippet_shell.py com.google.android.mobly.snippet.bundled`
```cmd
INFO:root:[AndroidDevice|d42f3582] Launching snippet apk com.google.android.mobly.snippet.bundled with protocol 1.0
ERROR:root:[AndroidDevice|d42f3582] Failed to start app and connect.
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 118, in start_app_and_connect
    self._start_app_and_connect()
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 164, in _start_app_and_connect
    raise ProtocolVersionError(self._ad, line)
mobly.controllers.android_device_lib.snippet_client.ProtocolVersionError: <AndroidDevice|d42f3582> INSTRUMENTATION_RESULT: shortMsg=Process crashed.
ERROR:root:[AndroidDevice|d42f3582] Failed to stop app after failure to start and connect.
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 118, in start_app_and_connect
    self._start_app_and_connect()
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 164, in _start_app_and_connect
    raise ProtocolVersionError(self._ad, line)
mobly.controllers.android_device_lib.snippet_client.ProtocolVersionError: <AndroidDevice|d42f3582> INSTRUMENTATION_RESULT: shortMsg=Process crashed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 127, in start_app_and_connect
    self.stop_app()
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 236, in stop_app
    'Failed to stop existing apk. Unexpected output: %s' % out)
mobly.controllers.android_device_lib.errors.DeviceError: <AndroidDevice|d42f3582> Failed to stop existing apk. Unexpected output: INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

Traceback (most recent call last):
  File "mobly\tools\snippet_shell.py", line 84, in <module>
    SnippetShell(package).main(args.serial)
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\jsonrpc_shell_base.py", line 88, in main
    self.start_console()
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\jsonrpc_shell_base.py", line 73, in start_console
    self._start_services(console_env)
  File "mobly\tools\snippet_shell.py", line 43, in _start_services
    self._ad.load_snippet(name='snippet', package=self._package)
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device.py", line 844, in load_snippet
    self.services.snippets.add_snippet_client(name, package)
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\services\snippet_management_service.py", line 86, in add_snippet_client
    client.start_app_and_connect()
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 132, in start_app_and_connect
    raise e
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 118, in start_app_and_connect
    self._start_app_and_connect()
  File "C:\Anaconda3\lib\site-packages\mobly\controllers\android_device_lib\snippet_client.py", line 164, in _start_app_and_connect
    raise ProtocolVersionError(self._ad, line)
mobly.controllers.android_device_lib.snippet_client.ProtocolVersionError: <AndroidDevice|d42f3582> INSTRUMENTATION_RESULT: shortMsg=Process crashed.
```

adb logcat:
```
03-07 12:10:12.203  1453  9837 I ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{com.google.android.mobly.snippet.bundled/com.google.android.mobly.snippet.SnippetRunner} results=Bundle[{shortMsg=Process crashed.}]
03-07 12:10:12.231  1453  1915 D CompatibilityInfo: mCompatibilityFlags - 10
03-07 12:10:12.231  1453  1915 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:12.231  1453  1915 D CompatibilityInfo: applicationScale - 1.0
03-07 12:10:12.249  1453  1915 D CompatibilityInfo: mCompatibilityFlags - 10
03-07 12:10:12.249  1453  1915 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:12.249  1453  1915 D CompatibilityInfo: applicationScale - 1.0
03-07 12:10:12.260  1453  1915 D CompatibilityInfo: mCompatibilityFlags - 10
03-07 12:10:12.260  1453  1915 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:12.260  1453  1915 D CompatibilityInfo: applicationScale - 1.0
03-07 12:10:12.523  9840  9840 W ADebug  : Failed to get property persist.sys.media.traces
03-07 12:10:12.538  9840  9840 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
03-07 12:10:12.711  9840  9840 D AndroidRuntime: Calling main entry com.android.commands.am.Am
03-07 12:10:12.756  1453  1915 I ActivityManager: Force stopping com.google.android.mobly.snippet.bundled appid=12251 user=0: start instr
03-07 12:10:12.798  9853  9853 I zygote64: Late-enabling -Xcheck:jni
03-07 12:10:12.800  1453  1915 D Boost   : hostingType=added application, hostingName=com.google.android.mobly.snippet.bundled, callerPackage=android, isSystem=true, isBoostNeeded=false.
03-07 12:10:12.801  1453  1915 I ActivityManager: Start proc 9853:com.google.android.mobly.snippet.bundled/u0a2251 for added application com.google.android.mobly.snippet.bundled caller=android
03-07 12:10:12.803  3686  3843 D PowerKeeper.Event: notifyAMProcStart processName: 12251 reason: com.google.android.mobly.snippet.bundled, pid:0
03-07 12:10:12.880  1453  2993 D CompatibilityInfo: mCompatibilityFlags - 0
03-07 12:10:12.880  1453  2993 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:12.880  1453  2993 D CompatibilityInfo: applicationScale - 1.0
03-07 12:10:12.910  9853  9853 W ResourceType: No package identifier when getting name for resource number 0x00000000
03-07 12:10:12.937  9853  9853 E InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
03-07 12:10:12.940  9853  9853 E MonitoringInstr: Exception encountered by: null. Dumping thread state to outputs and pining for the fjords.
03-07 12:10:12.940  9853  9853 E MonitoringInstr: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/com.google.android.mobly.snippet.bundled-JrU2-iQsOjoEiXV4lkaFjw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.mobly.snippet.bundled-JrU2-iQsOjoEiXV4lkaFjw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.app.LoadedApk.makeApplication(LoadedApk.java:972)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5851)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.os.Handler.dispatchMessage(Handler.java:105)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.os.Looper.loop(Looper.java:173)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at android.app.ActivityThread.main(ActivityThread.java:6698)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at java.lang.reflect.Method.invoke(Native Method)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-07 12:10:12.940  9853  9853 E MonitoringInstr:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:   Thread[main,5,main]
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     dalvik.system.VMStack.getThreadStackTrace(Native Method)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Thread.getStackTrace(Thread.java:1536)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Thread.getAllStackTraces(Thread.java:1586)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:643)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:638)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     androidx.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:632)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     androidx.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:522)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     android.app.LoadedApk.makeApplication(LoadedApk.java:976)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:5851)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     android.app.ActivityThread.-wrap1(Unknown Source:0)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     android.os.Handler.dispatchMessage(Handler.java:105)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     android.os.Looper.loop(Looper.java:173)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     android.app.ActivityThread.main(ActivityThread.java:6698)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.reflect.Method.invoke(Native Method)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:
03-07 12:10:12.944  9853  9853 E THREAD_STATE:   Thread[FinalizerDaemon,5,system]
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Object.wait(Native Method)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Object.wait(Object.java:422)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:234)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Daemons$Daemon.run(Daemons.java:105)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Thread.run(Thread.java:764)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:
03-07 12:10:12.944  9853  9853 E THREAD_STATE:   Thread[ReferenceQueueDaemon,5,system]
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Object.wait(Native Method)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:180)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Daemons$Daemon.run(Daemons.java:105)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Thread.run(Thread.java:764)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:
03-07 12:10:12.944  9853  9853 E THREAD_STATE:   Thread[FinalizerWatchdogDaemon,5,system]
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Object.wait(Native Method)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:299)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:279)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Daemons$Daemon.run(Daemons.java:105)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:     java.lang.Thread.run(Thread.java:764)
03-07 12:10:12.944  9853  9853 E THREAD_STATE:
03-07 12:10:12.944  9853  9853 E THREAD_STATE:   Thread[HeapTaskDaemon,5,system]
03-07 12:10:12.944  9853  9853 E THREAD_STATE:
03-07 12:10:12.944  9853  9853 E MonitoringInstr: Dying now...
03-07 12:10:12.945  9853  9853 D AndroidRuntime: Shutting down VM
03-07 12:10:12.947  9853  9853 E AndroidRuntime: FATAL EXCEPTION: main
03-07 12:10:12.947  9853  9853 E AndroidRuntime: Process: com.google.android.mobly.snippet.bundled, PID: 9853
03-07 12:10:12.947  9853  9853 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application android.support.multidex.MultiDexApplication: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/com.google.android.mobly.snippet.bundled-JrU2-iQsOjoEiXV4lkaFjw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.mobly.snippet.bundled-JrU2-iQsOjoEiXV4lkaFjw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:978)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5851)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:173)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6698)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
03-07 12:10:12.947  9853  9853 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/com.google.android.mobly.snippet.bundled-JrU2-iQsOjoEiXV4lkaFjw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.mobly.snippet.bundled-JrU2-iQsOjoEiXV4lkaFjw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:972)
03-07 12:10:12.947  9853  9853 E AndroidRuntime:        ... 9 more
03-07 12:10:12.969  2611  2649 I octvm_klo: klo lock
03-07 12:10:12.969  3686  3843 D PowerKeeper.Event: notifyAMCrash packageName: 0, pid:9853
03-07 12:10:12.974  1453  2993 D ActivityManager: report kill process: killerPid is:9853, killedPid is:9853
03-07 12:10:12.974  9853  9853 I Process : Sending signal. PID: 9853 SIG: 9
03-07 12:10:12.974  1453  2993 D ActivityManager: report kill process: killerPid is:9853, killedPid is:9853
03-07 12:10:12.981  2611  2649 I octvm_klo: get wanted event[mask:128, name:data_app_crash@1551931812980.txt] from the watchset
03-07 12:10:12.981  2611  2649 I octvm_klo: start gathering logcat log...
03-07 12:10:12.982  2611  2649 I octvm_klo: gathering logcat log done
03-07 12:10:12.982  2611  2649 I octvm_klo: klo unlock
03-07 12:10:12.983  1453  1524 D CompatibilityInfo: mCompatibilityFlags - 10
03-07 12:10:12.983  1453  1524 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:12.983  1453  1524 D CompatibilityInfo: applicationScale - 1.0
03-07 12:10:12.987  1453  2993 I ActivityManager: Process com.google.android.mobly.snippet.bundled (pid 9853) has died: fore FGS
03-07 12:10:12.988  1453  2993 W ActivityManager: Crash of app com.google.android.mobly.snippet.bundled running instrumentation ComponentInfo{com.google.android.mobly.snippet.bundled/com.google.android.mobly.snippet.SnippetRunner}
03-07 12:10:12.988  1453  2993 I ActivityManager: Force stopping com.google.android.mobly.snippet.bundled appid=12251 user=0: finished inst
03-07 12:10:12.988  1453  9837 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
03-07 12:10:12.988  1453  9837 W Binder  : java.lang.Throwable
03-07 12:10:12.988  1453  9837 W Binder  :      at android.os.BinderProxy.transact(Binder.java:743)
03-07 12:10:12.988  1453  9837 W Binder  :      at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:160)
03-07 12:10:12.988  1453  9837 W Binder  :      at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
03-07 12:10:12.992  1453  2997 D CompatibilityInfo: mCompatibilityFlags - 10
03-07 12:10:12.992  1453  2997 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:12.992  1453  2997 D CompatibilityInfo: applicationScale - 1.0
03-07 12:10:12.991  3686  3843 D PowerKeeper.Event: notifyAMProcDied pacakageName: com.google.android.mobly.snippet.bundled, pid:9853
03-07 12:10:12.992  9840  9840 D AndroidRuntime: Shutting down VM
03-07 12:10:13.001  1453  2993 D CompatibilityInfo: mCompatibilityFlags - 10
03-07 12:10:13.001  1453  2993 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:13.001  1453  2993 D CompatibilityInfo: applicationScale - 1.0
03-07 12:10:13.035  1453  2993 D CompatibilityInfo: mCompatibilityFlags - 10
03-07 12:10:13.035  1453  2993 D CompatibilityInfo: applicationDensity - 480
03-07 12:10:13.035  1453  2993 D CompatibilityInfo: applicationScale - 1.0
```

any suggestion? Thanks for your time!

**Comment by xpconanfan** [comment]
This just looks like you snippet apk crashed.
I'm not sure how your problem is related to this issue.
Please file a new issue if you think this is a framework problem, which I don't think it is.
