### ISSUE TITLE
adb call fails if numeric serial numbers are used

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#378]
If users use devices whose serials are entirely numeric and do not wrap the serial with quotation mark, we get:

```
Traceback (most recent call last):
  File ".../mobly/test_runner.py", line 420, in _register_controller
    objects = create(controller_config)
  File ".../mobly/controllers/android_device.py", line 87, in create
    ads = get_instances_with_configs(configs)
  File ".../mobly/controllers/android_device.py", line 257, in get_instances_with_configs
    ad = AndroidDevice(serial)
  File ".../mobly/controllers/android_device.py", line 402, in __init__
    if not self.is_bootloader and self.is_rootable:
  File ".../mobly/controllers/android_device.py", line 637, in is_rootable
    build_type_output = self.adb.getprop('ro.build.type').lower()
  File ".../mobly/controllers/android_device_lib/adb.py", line 175, in getprop
    return self.shell('getprop %s' % prop_name).decode('utf-8').strip()
  File ".../mobly/controllers/android_device_lib/adb.py", line 199, in adb_call
    clean_name, args, shell=shell, timeout=timeout)
  File ".../mobly/controllers/android_device_lib/adb.py", line 161, in _exec_adb_cmd
    return self._exec_cmd(adb_cmd, shell=shell, timeout=timeout)
  File ".../mobly/controllers/android_device_lib/adb.py", line 122, in _exec_cmd
    args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

**Comment by dthkao** [comment]
I think someone may have a integer instead of a string in their config:
`['adb', '-s', <serial>, 'shell', 'getprop', 'ro.build.id']`
<serial> is in the index 2 spot

**Comment by dthkao** [comment]
We should do a type check here: https://github.com/google/mobly/blob/7a7ffb82bf8786f645c5117322e9d83c337903fd/mobly/controllers/android_device.py#L429
