### ISSUE TITLE
adb forward --list fails when two or more devices are connected.

### ISSUE THREAD

**Issue by Darren** [google/mobly#477]
$ adb version:

```
Android Debug Bridge version 1.0.40
Version 4797878
Installed as /usr/local/bin/adb
```

$ adb devices:

```
List of devices attached
3600S001741402513	device
3600S002751108386	device
```

$ snippet_shell.py -s 3600S002751108386  com.webterren.mobly

```

INFO:root:[AndroidDevice|3600S002751108386] Launching snippet apk com.webterren.mobly with protocol 1.0
ERROR:root:[AndroidDevice|3600S002751108386] Failed to start app and connect.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mobly-1.7.3-py2.7.egg/mobly/controllers/android_device.py", line 879, in load_snippet
    client.start_app_and_connect()
  File "/usr/local/lib/python2.7/site-packages/mobly-1.7.3-py2.7.egg/mobly/controllers/android_device_lib/snippet_client.py", line 120, in start_app_and_connect
    self.host_port = utils.get_available_host_port()
  File "/usr/local/lib/python2.7/site-packages/mobly-1.7.3-py2.7.egg/mobly/utils.py", line 417, in get_available_host_port
    if port not in adb.list_occupied_adb_ports():
  File "/usr/local/lib/python2.7/site-packages/mobly-1.7.3-py2.7.egg/mobly/controllers/android_device_lib/adb.py", line 89, in list_occupied_adb_ports
    out = AdbProxy().forward('--list')
  File "/usr/local/lib/python2.7/site-packages/mobly-1.7.3-py2.7.egg/mobly/controllers/android_device_lib/adb.py", line 317, in forward
    'forward', args, shell, timeout=None, stderr=None)
  File "/usr/local/lib/python2.7/site-packages/mobly-1.7.3-py2.7.egg/mobly/controllers/android_device_lib/adb.py", line 273, in _exec_adb_cmd
    adb_cmd, shell=shell, timeout=timeout, stderr=stderr)
  File "/usr/local/lib/python2.7/site-packages/mobly-1.7.3-py2.7.egg/mobly/controllers/android_device_lib/adb.py", line 182, in _exec_cmd
    raise AdbError(cmd=args, stdout=out, stderr=err, ret_code=ret)
AdbError: Error executing adb cmd "adb forward --list". ret: 1, stdout: , stderr: error: unknown host service
```

**Comment by xpconanfan** [comment]
Thanks so much for reporting!
You are ahead of us on this :)

This issue actually looks like a bug in adb behavior of 1.0.40.
I have filed an internal bug to adb team.
