### ISSUE TITLE
ad.reboot does not work on non-root devices

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#65]
Calling ad.reboot causes error:
[testbedB] 12-27 16:00:18.368 INFO [Test Case] test_hello
[testbedB] 12-27 16:00:18.392 ERROR Process 6561 has terminated. ret: 0, stderr: , stdout:
Traceback (most recent call last):
  File "/Users/angli/Developer/mobly/mobly/base_test.py", line 307, in exec_one_testcase
    self._setup_test(test_name)
  File "/Users/angli/Developer/mobly/mobly/base_test.py", line 157, in _setup_test
    self.setup_test()
  File "/Users/angli/Desktop/SampleTest.py", line 31, in setup_test
    self.ad.reboot()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 808, in reboot
    self.stop_services()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 420, in stop_services
    self.stop_adb_logcat()
  File "/Users/angli/Developer/mobly/mobly/controllers/android_device.py", line 694, in stop_adb_logcat
    utils.stop_standing_subprocess(self._adb_logcat_process)
  File "/Users/angli/Developer/mobly/mobly/utils.py", line 353, in stop_standing_subprocess
    _assert_subprocess_running(proc)
  File "/Users/angli/Developer/mobly/mobly/utils.py", line 304, in _assert_subprocess_running
    " stdout: %s" % (proc.pid, ret, err, out))
Error: Process 6561 has terminated. ret: 0, stderr: , stdout:

**Comment by xpconanfan** [comment]
Real issue is actually #66, closing this
