### ISSUE TITLE
Add feature re-connect with android app for `snippet_shell.py` 

### ISSUE THREAD

**Issue by mrttson** [google/mobly#660]
I got this error after re-install `mobly-bundled-snippets` 
```
>>> s.help()
Traceback (most recent call last):
  File "D:\Programs\anaconda3\lib\site-packages\mobly-1.9.1-py3.7.egg\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 278, in _client_receive
    response = self._client.readline()
  File "D:\Programs\anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\Programs\anaconda3\lib\site-packages\mobly-1.9.1-py3.7.egg\mobly\controllers\android_device_lib\snippet_client.py", line 356, in help
    help_text = self._rpc('help')
  File "D:\Programs\anaconda3\lib\site-packages\mobly-1.9.1-py3.7.egg\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 320, in _rpc
    response = self._client_receive()
  File "D:\Programs\anaconda3\lib\site-packages\mobly-1.9.1-py3.7.egg\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 284, in _client_receive
    'Encountered socket error reading RPC response "%s"' % e)
mobly.controllers.android_device_lib.jsonrpc_client_base.Error: <AndroidDevice|5200b9494d8c749d> Encountered socket error reading RPC response "[WinError 10053] An established connection was aborted by the software in your host machine"
```

And i have to exit the console then re-connect to android app every time i re-install the app.
`python .\snippet_shell.py com.google.android.mobly.snippet.bundled`

Could you guys add feature to re-connect with android app into `snippet_shell.py`?
Some thing like `ad.reconnect()`

**Comment by xpconanfan** [comment]
That is surprising.
This is not reproducible for me. Is there any more info you can provide? Like what computer you are using and what Android device you have?

**Comment by mrttson** [comment]
PC OS: Windows 10
Phone: Samsung Galaxy A8 2018

**Comment by mrttson** [comment]
I have 2 adb executable exist on PATH variable, the issue gone after remove redundant one.
