### ISSUE TITLE
AndroidDevice object doesn't clean up correctly in interactive mode

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#77]
If the object is obtained by directly calling android_device.get_all_instances instead of android_device.create, the device object will try to stop SL4A even if SL4A is not started in the first place.
```
>>> from mobly.controllers import android_device
>>> ad = android_device.get_all_instances()[0]
>>> ad.stop_services()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device.py", line 417, in stop_services
    self._terminate_jsonrpc_client(client)
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device.py", line 574, in _terminate_jsonrpc_client
    client.closeSl4aSession()
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 292, in rpc_call
    return self._rpc(name, *args)
  File "/usr/local/google/home/angli/Developer/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 281, in _rpc
    raise ProtocolError(ProtocolError.NO_RESPONSE_FROM_SERVER)
mobly.controllers.android_device_lib.jsonrpc_client_base.ProtocolError: No response from server.
```

**Comment by xpconanfan** [comment]
This is not reproducible any more
