### ISSUE TITLE
am getting error while running the hello_world_test.py script

### ISSUE THREAD

**Issue by nishanthninja** [google/mobly#845]
error logpython hello_world_test.py -c sample_config.yml
[SampleTestBed] 07-30 10:21:18.297 INFO ==========> HelloWorldTest <==========
[SampleTestBed] 07-30 10:21:18.301 ERROR Failed to initialize objects for controller AndroidDevice, abort!
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controller_manager.py", line 121, in register_controller
    objects = module.create(controller_config)
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device.py", line 105, in create
    ads = get_all_instances()
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device.py", line 323, in get_all_instances
    return get_instances(list_adb_devices())
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device.py", line 219, in list_adb_devices
    out = adb.AdbProxy().devices()
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device_lib\adb.py", line 548, in adb_call
    return self._exec_adb_cmd(name,
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device_lib\adb.py", line 290, in _exec_adb_cmd
    out = self._exec_cmd(adb_cmd, shell=shell, timeout=timeout, stderr=stderr)
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device_lib\adb.py", line 186, in _exec_cmd
    (ret, out, err) = utils.run_command(args, shell=shell, timeout=timeout)
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\utils.py", line 455, in run_command
    process = subprocess.Popen(cmd,
  File "C:\Program Files\python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
[SampleTestBed] 07-30 10:21:18.307 ERROR Error in HelloWorldTest#setup_class.
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\base_test.py", line 393, in _setup_class
    self.setup_class()
  File "C:\Users\nisha\OneDrive\Documents\test\hello_world_test.py", line 12, in setup_class
    self.ads = self.register_controller(android_device)
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\base_test.py", line 332, in register_controller
    return self._controller_manager.register_controller(module, required,
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controller_manager.py", line 121, in register_controller
    objects = module.create(controller_config)
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device.py", line 105, in create
    ads = get_all_instances()
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device.py", line 323, in get_all_instances
    return get_instances(list_adb_devices())
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device.py", line 219, in list_adb_devices
    out = adb.AdbProxy().devices()
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device_lib\adb.py", line 548, in adb_call
    return self._exec_adb_cmd(name,
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device_lib\adb.py", line 290, in _exec_adb_cmd
    out = self._exec_cmd(adb_cmd, shell=shell, timeout=timeout, stderr=stderr)
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\controllers\android_device_lib\adb.py", line 186, in _exec_cmd
    (ret, out, err) = utils.run_command(args, shell=shell, timeout=timeout)
  File "C:\Program Files\python\lib\site-packages\mobly-1.11.1-py3.10.egg\mobly\utils.py", line 455, in run_command
    process = subprocess.Popen(cmd,
  File "C:\Program Files\python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
[SampleTestBed] 07-30 10:21:18.333 INFO Summary for test class HelloWorldTest: Error 1, Executed 0, Failed 0, Passed 0, Requested 1, Skipped 1
[SampleTestBed] 07-30 10:21:18.337 INFO Summary for test run SampleTestBed@07-30-2022_10-21-18-177:
Total time elapsed 0.04208840000501368s
Artifacts are saved in "C:\tmp\logs\mobly\SampleTestBed\07-30-2022_10-21-18-177"
Test results: Error 1, Executed 0, Failed 0, Passed 0, Requested 1, Skipped 1

as i am new here to mobly can some one help me with the issue ? 
i just check and issue which was on 2016 but dint fetch the solution 
adb screenshot: 
![image](https://user-images.githubusercontent.com/110274886/181875525-46eb83a9-e0da-41c9-88f6-e28656c3390a.png)

**Comment by nishanthninja** [comment]
![image](https://user-images.githubusercontent.com/110274886/181876390-73159102-78cc-45d5-a39b-5ff96190d65c.png)
![image](https://user-images.githubusercontent.com/110274886/181876405-71102c94-4f15-45c0-82f9-744eec7b0d3a.png)

**Comment by xpconanfan** [comment]
As the error message says, "FileNotFoundError: [WinError 2] The system cannot find the file specified"
You need to figure out why the file is not found.

And it looks like your `adb` is not set up properly

**Comment by nishanthninja** [comment]
@xpconanfan can you please help what needs to be done, i added the adb path to env path but now i am not able to install the mentioned apk on the device. I have attached image for it

![image](https://user-images.githubusercontent.com/110274886/182009622-f46570f0-32aa-4553-b1ba-a2c01ea68f38.png)

**Comment by xpconanfan** [comment]
This is an issue with our local environment.
There isn't anything we can do.
