### ISSUE TITLE
Unable to shutdown sl4a event dispatcher.

### ISSUE THREAD

**Issue by ibrahim141446** [google/mobly#927]
### Discussed in https://github.com/google/mobly/discussions/926

<div type='discussions-op-text'>

<sup>Originally posted by **ibrahim141446** July 25, 2024</sup>
I am using latest mobly version : 1.12.3

I am running the tests, after the test is getting completed, I am getting this error . i tried to debug it, i came to know the clean is happening twice, so the second time cleaning of host port is causing this error, how to eliminate this error

Error:
------
WARNING:root:The module mobly.controllers.android_device_lib.snippet_event is deprecated and will be removed in a future version. Use module mobly.snippet.callback_event instead.
WARNING:root:The module mobly.controllers.android_device_lib.callback_handler is deprecated and will be removed in a future version. Use module mobly.controllers.android_device_lib.callback_handler_v2 instead.
[SampleTestBed] 07-25 15:28:10.364 INFO ==========> FunctionalityTest <==========
[SampleTestBed] 07-25 15:28:17.833 WARNING The method mobly.utils.get_available_host_port is deprecated because it is unreliable. Pass "tcp:0" to adb forward instead.
[SampleTestBed] 07-25 15:28:22.156 INFO [Test] test_sample
Sample Test
[SampleTestBed] 07-25 15:28:22.156 INFO [Test] test_sample PASS
[SampleTestBed] 07-25 15:28:22.484 ERROR [AndroidDevice|<serialnumber>] Failed to shutdown sl4a event dispatcher.
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\sl4a_client.py", line 131, in stop_event_dispatcher
    self.ed.clean_up()
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\event_dispatcher.py", line 150, in clean_up
    self._sl4a.disconnect()
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 247, in disconnect
    self.clear_host_port()
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 258, in clear_host_port
    self._ad.adb.forward(['--remove', 'tcp:%d' % self.host_port])
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\adb.py", line 458, in forward
    return self._exec_adb_cmd(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\adb.py", line 309, in _exec_adb_cmd
    out = self._exec_cmd(adb_cmd, shell=shell, timeout=timeout, stderr=stderr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\adb.py", line 211, in _exec_cmd
    raise AdbError(
mobly.controllers.android_device_lib.adb.AdbError: Error executing adb cmd "adb -s <serialnumber> forward --remove tcp:59078". ret: 1, stdout: b'', stderr: b"adb.exe: error: listener 'tcp:59078' not found\r\n"
[SampleTestBed] 07-25 15:28:24.321 INFO Summary for test class FunctionalityTest: Error 0, Executed 1, Failed 0, Passed 1, Requested 1, Skipped 0
[SampleTestBed] 07-25 15:28:24.321 INFO Summary for test run SampleTestBed@07-25-2024_15-28-10-139:
Total time elapsed 13.95902309997473s
Artifacts are saved in "C:\tmp\logs\mobly\SampleTestBed\07-25-2024_15-28-10-139"
Test summary saved in "C:\tmp\logs\mobly\SampleTestBed\07-25-2024_15-28-10-139\test_summary.yaml"
Test results: Error 0, Executed 1, Failed 0, Passed 1, Requested 1, Skipped 0
Exception ignored in: <function JsonRpcClientBase.__del__ at 0x0000019AC59AFA60>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 131, in __del__
    self.disconnect()
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 247, in disconnect
    self.clear_host_port()
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 258, in clear_host_port
    self._ad.adb.forward(['--remove', 'tcp:%d' % self.host_port])
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\adb.py", line 458, in forward
    return self._exec_adb_cmd(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\adb.py", line 309, in _exec_adb_cmd
    out = self._exec_cmd(adb_cmd, shell=shell, timeout=timeout, stderr=stderr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\android_device_lib\adb.py", line 195, in _exec_cmd
    (ret, out, err) = utils.run_command(args, shell=shell, timeout=timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\utils.py", line 491, in run_command
    out, err = process.communicate()
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1612, in _communicate
    self.stdout_thread.start()
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown</div>

**Comment by xpconanfan** [comment]
sl4a related code has been deprecated for over a year, and they will be removed soon.
please migrate to snippet instead.
