### ISSUE TITLE
Failed to collect CIM instance of class: Win32_PnPEntity

### ISSUE THREAD

**Issue by dyingfair** [google/mobly#946]
Hello，Please help solve this issue： 

---------------------------------------------------------------
ERROR [WindowsDevice|169.254.8.100:22] An error occurred but ignored when collecting `<class 'mobly.controllers.windows.lib.win32_cim_info.OperatingSystemInfo'>`.
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 665, in _get_cim_instances
    return json.loads(result)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 587, in _collect_build_info
    cim_instance = _get_cim_instances(ssh, cim_class_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 667, in _get_cim_instances
    raise errors.CimInstanceError(
mobly.controllers.windows.lib.errors.CimInstanceError: Failed to collect CIM instance of class: Win32_OperatingSystem
[MagicLinkTest] 11-13 14:11:36.880 ERROR [WindowsDevice|169.254.8.100:22] An error occurred but ignored when collecting `<class 'mobly.controllers.windows.lib.win32_cim_info.LogicalDiskInfo'>`.
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 846, in decode_bytes
    return raw_bytes.decode(_DEFAULT_ENCODING_POWERSHELL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\encodings\utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 6076: truncated data
decoding with 'UTF-16LE' codec failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 264, in execute_command
    stdout_str = decode_bytes(stdout_file.read())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 848, in decode_bytes
    raise errors.DecodeError(
mobly.controllers.windows.lib.errors.DecodeError: Cannot decode byets stream, try to decode with cp1252 and utf-16LE both failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 664, in _get_cim_instances
    result = ssh.execute_ps_command(cmd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 356, in execute_ps_command
    self.execute_command(
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 268, in execute_command
    raise errors.SshRemoteError(
mobly.controllers.windows.lib.errors.SshRemoteError: <SSHProxy|169.254.8.100:22> Failed to decode output of command: powershell -encodedcommand RwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBMAG8AZwBpAGMAYQBsAEQAaQBzAGsAIAB8ACAAQwBvAG4AdgBlAHIAdABUAG8ALQBKAHMAbwBuACAALQBDAG8AbQBwAHIAZQBzAHMA

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 630, in _collect_build_info_list
    cim_instances = _get_cim_instances(ssh, cim_class_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 667, in _get_cim_instances
    raise errors.CimInstanceError(
mobly.controllers.windows.lib.errors.CimInstanceError: Failed to collect CIM instance of class: Win32_LogicalDisk
[MagicLinkTest] 11-13 14:11:46.230 ERROR [WindowsDevice|169.254.8.100:22] An error occurred but ignored when collecting `<class 'mobly.controllers.windows.lib.win32_cim_info.TimeLocaleInfo'>`.
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 846, in decode_bytes
    return raw_bytes.decode(_DEFAULT_ENCODING_POWERSHELL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\encodings\utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 4246: truncated data
decoding with 'UTF-16LE' codec failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 264, in execute_command
    stdout_str = decode_bytes(stdout_file.read())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 848, in decode_bytes
    raise errors.DecodeError(
mobly.controllers.windows.lib.errors.DecodeError: Cannot decode byets stream, try to decode with cp1252 and utf-16LE both failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 536, in collect
    sys_info = ssh.execute_ps_command('systeminfo')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 356, in execute_ps_command
    self.execute_command(
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\ssh.py", line 268, in execute_command
    raise errors.SshRemoteError(
mobly.controllers.windows.lib.errors.SshRemoteError: <SSHProxy|169.254.8.100:22> Failed to decode output of command: powershell -encodedcommand cwB5AHMAdABlAG0AaQBuAGYAbwA=
[MagicLinkTest] 11-13 14:11:47.702 ERROR [WindowsDevice|169.254.8.100:22] An error occurred but ignored when collecting `<class 'mobly.controllers.windows.lib.win32_cim_info.PnPEntityInfo'>`.
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 665, in _get_cim_instances
    return json.loads(result)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 630, in _collect_build_info_list
    cim_instances = _get_cim_instances(ssh, cim_class_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\site-packages\mobly\controllers\windows\lib\win32_cim_info.py", line 667, in _get_cim_instances
    raise errors.CimInstanceError(
mobly.controllers.windows.lib.errors.CimInstanceError: Failed to collect CIM instance of class: Win32_PnPEntity

**Comment by xpconanfan** [comment]
```
'utf-16-le' codec can't decode byte 0x0a in position 4246: truncated data
```

We are not here to debug your code for you. Debug your own code.
